#!/bin/bash

git submodule init
git submodule update

cd

ln -s MyUnixEnv/.bash_gitprompt .bash_gitprompt
ln -s MyUnixEnv/.bash_profile .bash_profile
ln -s MyUnixEnv/.bashrc .bashrc
ln -s MyUnixEnv/.config .config
ln -s MyUnixEnv/.eslintrc.json .eslintrc.json
ln -s MyUnixEnv/.ghci .ghci
ln -s MyUnixEnv/.gitconfig .gitconfig
ln -s MyUnixEnv/.gvimrc .gvimrc
ln -s MyUnixEnv/.haskeline .haskeline
ln -s MyUnixEnv/.jshintrc .jshintrc
ln -s MyUnixEnv/.prettieropts .prettieropts
ln -s MyUnixEnv/.tern-project .tern-project
ln -s MyUnixEnv/.tmux .tmux
ln -s MyUnixEnv/.tmux.conf .tmux.conf
ln -s MyUnixEnv/.vim .vim
ln -s MyUnixEnv/.vimrc .vimrc
ln -s MyUnixEnv/.vintrc.yaml .vintrc.yaml
ln -s MyUnixEnv/mytmux mytmux

mkdir -p bin
cp MyUnixEnv/bin/* bin

#cp -f MyUnixEnv/javascript.snippets .vim/bundle/snipmate.vim/snippets

tic MyUnixEnv/xterm-256color-italic.terminfo
tic MyUnixEnv/screen-256color-italic.terminfo
tic MyUnixEnv/tmux-256color-italic.terminfo
# Don't forget to change iTerm preferences!
# Under Profiles...Text,
# change the font to one that supports italic
# and verify that "Italic text allowed" is checked.
# Under Profiles...Terminal, change "Report Terminal Type"
# to xterm-256color-italic.

echo Success!
echo See comments in the setup script for additional manual steps!
