#!/bin/bash

git submodule init
git submodule update

cd

ln -s MyUnixEnv/.bash_gitprompt .bash_gitprompt
ln -s MyUnixEnv/.bash_profile .bash_profile
ln -s MyUnixEnv/.bashrc .bashrc
ln -s MyUnixEnv/.eslintrc.json .eslintrc.json
ln -s MyUnixEnv/.gitconfig .gitconfig
ln -s MyUnixEnv/.gvimrc .gvimrc
ln -s MyUnixEnv/.jshintrc .jshintrc
ln -s MyUnixEnv/.tmux .tmux
ln -s MyUnixEnv/.tmux.conf .tmux.conf
ln -s MyUnixEnv/.vim .vim
ln -s MyUnixEnv/.vimrc .vimrc
ln -s MyUnixEnv/mytmux mytmux

mkdir -p bin
cp MyUnixEnv/bin/* bin

#cp -f MyUnixEnv/javascript.snippets .vim/bundle/snipmate.vim/snippets

echo success!
