git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side
    # pager: ydiff -p cat -s --wrap --width=40
    useConfig: true
gui:
  showIcons:
    true
    # sidePanelWidth: 0.2 # gives more space to show side-by-side
keybinding:
  universal:
    quit-alt1: "<esc>" # This does not work.
    # quit-alt1: "<c-c>" # This works!
