git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side
    # pager: ydiff -p cat -s --wrap --width=40
    useConfig: true
gui:
  showIcons:
    true
    # sidePanelWidth: 0.2 # gives more space to show side-by-side
