return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = { "windwp/nvim-ts-autotag", "JoosepAlviste/nvim-ts-context-commentstring" },
  event = "User AstroFile",
  cmd = {
    "TSBufDisable",
    "TSBufEnable",
    "TSBufToggle",
    "TSDisable",
    "TSEnable",
    "TSToggle",
    "TSInstall",
    "TSInstallInfo",
    "TSInstallSync",
    "TSModuleInfo",
    "TSUninstall",
    "TSUpdate",
    "TSUpdateSync",
  },
  build = ":TSUpdate",
  opts = {
    autotag = { enable = true },
    context_commentstring = { enable = true, enable_autocmd = false },
    ensure_installed = { "javascript", "lua", "typescript" },
    highlight = { enable = true },
    incremental_selection = { enable = true },
    indent = { enable = true },
  },
  config = require "plugins.configs.nvim-treesitter",
}
